[v1]
"dump_syms 2.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["dump_syms"]
"minidump-stackwalk 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["minidump-stackwalk"]
